settings:
    survival:
        sign:
            delay: 10 #set the delay for someone warping using a sign in survival
            allow-move: false #should the player that's warping be allowed to move?
        command:
            delay: 10
            allow-move: false
    creative:
        sign:
            delay: 0
            allow-move: true
        command:
            delay: 0
            allow-move: true
effects:
    arrival:
        sign:
            effect: portal #the effect played when a player arrives after warping using a sign
            count: 50 #the amount of times the effect is played
        command:
            effect: portal
            count: 50
    departure:
        sign:
            effect: flame
            count: 500
        command:
            effect: flame
            count: 500